export type BreakLength = "short" | "medium" | "long";

export const breakRecommendations: Record<BreakLength, string[]> = {
  short: [
    "break.short.1",
    "break.short.2",
    "break.short.3",
    "break.short.4",
    "break.short.5",
    "break.short.6",
    "break.short.7",
    "break.short.8",
    "break.short.9",
    "break.short.10",
    "break.short.11",
    "break.short.12",
  ],
  medium: [
    "break.medium.1",
    "break.medium.2",
    "break.medium.3",
    "break.medium.4",
    "break.medium.5",
    "break.medium.6",
    "break.medium.7",
    "break.medium.8",
    "break.medium.9",
    "break.medium.10",
    "break.medium.11",
    "break.medium.12",
  ],
  long: [
    "break.long.1",
    "break.long.2",
    "break.long.3",
    "break.long.4",
    "break.long.5",
    "break.long.6",
    "break.long.7",
    "break.long.8",
    "break.long.9",
    "break.long.10",
    "break.long.11",
    "break.long.12",
  ],
};
